<a href="https://colab.research.google.com/github/i-m-alive/NLP-Projects-and-Practices/blob/main/LSTM_Next_Word_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import pandas as pd

# Load CSV file
df = pd.read_csv('/content/drive/MyDrive/Project/project dataset/insparation.csv')

In [4]:
Quotes = df['Quote']

In [5]:
Quotes

0                           Let us see what love can do. 
1       We can’t heal the world today. But we can begi...
2       Listen with curiosity. Speak with honesty. Act...
3       The most basic and powerful way to connect to ...
4                  Knowledge speaks, but wisdom listens. 
                              ...                        
1741    I was set free because my greatest fear had be...
1742    Comedy is defiance. It's a snort of contempt i...
1743    Every piece of the universe, even the tiniest ...
1744    Take a stand for what's right. Raise a ruckus ...
1745    There's something about love that people just ...
Name: Quote, Length: 1746, dtype: object

In [6]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer


The Tokenizer class in tensorflow.keras.preprocessing.text module is used to vectorize a text corpus into a list of integers. Each integer represents the index of a word in a vocabulary dictionary. It provides methods to tokenize a text corpus, create a word index, and convert text data into sequences of integers.

In [7]:
tokenizer= Tokenizer()

In [8]:
tokenizer.fit_on_texts(Quotes)

In [9]:
#to view the words with their token names
tokenizer.word_index

{'the': 1,
 'to': 2,
 'is': 3,
 'you': 4,
 'and': 5,
 'of': 6,
 'a': 7,
 'in': 8,
 'it': 9,
 'that': 10,
 'we': 11,
 'be': 12,
 'your': 13,
 'for': 14,
 'not': 15,
 'are': 16,
 'i': 17,
 'can': 18,
 'what': 19,
 'have': 20,
 'do': 21,
 'life': 22,
 'but': 23,
 'with': 24,
 'all': 25,
 'will': 26,
 'who': 27,
 'our': 28,
 'love': 29,
 'one': 30,
 'if': 31,
 'as': 32,
 'by': 33,
 'there': 34,
 'world': 35,
 'when': 36,
 'no': 37,
 'things': 38,
 'more': 39,
 'on': 40,
 'than': 41,
 'they': 42,
 'make': 43,
 'only': 44,
 'people': 45,
 'or': 46,
 'others': 47,
 'yourself': 48,
 'good': 49,
 'us': 50,
 'an': 51,
 'about': 52,
 'never': 53,
 'heart': 54,
 'my': 55,
 'from': 56,
 'most': 57,
 'always': 58,
 'how': 59,
 'up': 60,
 'just': 61,
 'those': 62,
 'must': 63,
 'way': 64,
 'know': 65,
 'something': 66,
 'work': 67,
 'their': 68,
 'give': 69,
 'being': 70,
 'this': 71,
 'at': 72,
 'them': 73,
 'thing': 74,
 "it's": 75,
 'time': 76,
 'so': 77,
 'out': 78,
 'like': 79,
 'live': 80,
 'ki

In [10]:
len(tokenizer.word_index)# total no. of unique words

3763

In [11]:
#sentence with their word sequences represented as numbers or say vectors
for sentence in Quotes:
    print(tokenizer.texts_to_sequences([sentence])[0])

[99, 50, 113, 19, 29, 18, 21]
[11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24, 7, 466, 6, 116, 7, 54, 6, 29, 5, 51, 187, 6, 81]
[179, 24, 561, 336, 24, 426, 187, 24, 318]
[1, 57, 636, 5, 214, 64, 2, 637, 2, 149, 119, 3, 2, 179, 61, 179]
[363, 1314, 23, 198, 1918]
[508, 272, 3, 1, 127, 6, 272, 10, 18, 209, 1315, 1, 562, 6, 149, 119]
[82, 119, 8, 71, 22, 100, 66, 2, 1919, 32, 854, 32, 4, 273, 10, 4, 274, 48, 2, 364, 272]
[34, 16, 37, 389, 11, 90, 1023, 215, 5, 319, 467, 10, 11, 18, 1023, 33, 171]
[17, 58, 1920, 390, 391, 1316, 21, 66, 52, 10, 124, 17, 1317, 10, 17, 144, 391]
[99, 50, 563, 233, 14, 25, 130, 38, 99, 50, 188, 2, 1024, 1921, 5, 1922, 24, 365, 116, 5, 29]
[11, 161, 1923, 26, 199, 1924, 23, 37, 75, 19, 11, 21, 10, 721, 722, 1, 189]
[36, 30, 1925, 72, 7, 427, 74, 8, 200, 30, 723, 9, 1926, 2, 1, 428, 6, 1, 35]
[21, 15, 564, 87, 33, 55, 135, 564, 87, 33, 59, 254, 284, 17, 1025, 234, 5, 855, 181, 60, 216]
[17, 18, 12, 1026, 33, 19, 509, 2, 87, 23, 17, 856, 2, 12, 1927, 33, 9]
[150,

In [12]:
input_sequences = []
for sentence in Quotes:
    tokenized_sentence= (tokenizer.texts_to_sequences([sentence])[0])

    for i in range(1,len(tokenized_sentence)):
       input_sequences.append(tokenized_sentence[:i+1])
#perfroming  slicing(tokenized_sentence[:i+1]) and appending to a new list


this will replace all the words with their respective index no. or say token no in each and every line. for trainng the model for text generation we need to have a dataset which will give input as the sequence of the sentence one word at a time and the output as the next words after each entry


In [13]:
input_sequences

[[99, 50],
 [99, 50, 113],
 [99, 50, 113, 19],
 [99, 50, 113, 19, 29],
 [99, 50, 113, 19, 29, 18],
 [99, 50, 113, 19, 29, 18, 21],
 [11, 335],
 [11, 335, 634],
 [11, 335, 634, 1],
 [11, 335, 634, 1, 35],
 [11, 335, 634, 1, 35, 197],
 [11, 335, 634, 1, 35, 197, 23],
 [11, 335, 634, 1, 35, 197, 23, 11],
 [11, 335, 634, 1, 35, 197, 23, 11, 18],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24, 7],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24, 7, 466],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24, 7, 466, 6],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24, 7, 466, 6, 116],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24, 7, 466, 6, 116, 7],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24, 7, 466, 6, 116, 7, 54],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24, 7, 466, 6, 116, 7, 54, 6],
 [11, 335, 634, 1, 35, 197, 23, 11, 18, 635, 24, 7, 466, 6, 116, 7, 54, 6, 29],
 [11,
  335,
  634,
  1,

In [14]:
#we will find the length of the longest list so that we can apply padding
max_len = max(len(x) for x in input_sequences)

In [15]:
max_len

115

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences,maxlen = max_len,padding="pre")

For perfroming paddding there is already a function in keras so we will import that function

In [17]:
padded_input_sequences

array([[   0,    0,    0, ...,    0,   99,   50],
       [   0,    0,    0, ...,   99,   50,  113],
       [   0,    0,    0, ...,   50,  113,   19],
       ...,
       [   0,    0,    0, ...,   61,   20,    2],
       [   0,    0,    0, ...,   20,    2, 1093],
       [   0,    0,    0, ...,    2, 1093,    2]], dtype=int32)

In [18]:
x=padded_input_sequences[:,:-1] #using slice operation

In [19]:
y=padded_input_sequences[:,-1]

In [20]:
x,y

(array([[   0,    0,    0, ...,    0,    0,   99],
        [   0,    0,    0, ...,    0,   99,   50],
        [   0,    0,    0, ...,   99,   50,  113],
        ...,
        [   0,    0,    0, ...,   45,   61,   20],
        [   0,    0,    0, ...,   61,   20,    2],
        [   0,    0,    0, ...,   20,    2, 1093]], dtype=int32),
 array([  50,  113,   19, ...,    2, 1093,    2], dtype=int32))

In [21]:
 x.shape

(33903, 114)

In [22]:
 y.shape

(33903,)

In [23]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=3764)
#used to perform One hot encoding

In [24]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [25]:
y.shape

(33903, 3764)

In [26]:
#importing necessery libraries
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense


In [27]:

# Define the model
model = Sequential()

# Add an Embedding layer
model.add(Embedding(input_dim=3764, output_dim=200, input_length=114))

# Add LSTM layers
model.add(LSTM(units=150, return_sequences=True))  # First LSTM layer returning sequences
model.add(LSTM(units=150))  # Second LSTM layer not returning sequences

# Add Dense layer
model.add(Dense(3764, activation='softmax'))

In [28]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 114, 200)          752800    
                                                                 
 lstm (LSTM)                 (None, 114, 150)          210600    
                                                                 
 lstm_1 (LSTM)               (None, 150)               180600    
                                                                 
 dense (Dense)               (None, 3764)              568364    
                                                                 
Total params: 1712364 (6.53 MB)
Trainable params: 1712364 (6.53 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [30]:
model.fit(x,y,epochs=100,verbose=1)

Epoch 1/100
1060/1060 [==============================] - 46s 39ms/step - loss: 6.3054 - accuracy: 0.0562
Epoch 2/100
1060/1060 [==============================] - 17s 16ms/step - loss: 5.8287 - accuracy: 0.0856
Epoch 3/100
1060/1060 [==============================] - 15s 14ms/step - loss: 5.5512 - accuracy: 0.1076
Epoch 4/100
1060/1060 [==============================] - 15s 14ms/step - loss: 5.3506 - accuracy: 0.1254
Epoch 5/100
1060/1060 [==============================] - 14s 13ms/step - loss: 5.1533 - accuracy: 0.1400
Epoch 6/100
1060/1060 [==============================] - 14s 13ms/step - loss: 4.9725 - accuracy: 0.1489
Epoch 7/100
1060/1060 [==============================] - 15s 14ms/step - loss: 4.8076 - accuracy: 0.1580
Epoch 8/100
1060/1060 [==============================] - 14s 13ms/step - loss: 4.6538 - accuracy: 0.1649
Epoch 9/100
1060/1060 [==============================] - 14s 13ms/step - loss: 4.5028 - accuracy: 0.1737
Epoch 10/100
1060/1060 [==============================]

In [60]:
text='about'

#tokenize
token_text=tokenizer.texts_to_sequences([text])[0]
#padding
padded_input=pad_sequences([token_text],maxlen=114,padding='pre')
print(padded_input)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 52]]


In [61]:
#predict
predict =model.predict(padded_input)
import numpy as np
p=np.argmax(predict)

1/1 [==============================] - 0s 20ms/step


In [62]:
for word, index in tokenizer.word_index.items():
  if index == p:
    print(word)

your


In [66]:
# for predicting 5 words
text="about"
for i in range(5):
  #tokenize
  token_text=tokenizer.texts_to_sequences([text])[0]
  #padding
  padded_input=pad_sequences([token_text],maxlen=114,padding='pre')
  #predict
  predict =np.argmax(model.predict(padded_input))
  for word, index in tokenizer.word_index.items():
    if index == predict:
      text = text + " "+ word
      print(text)

1/1 [==============================] - 0s 31ms/step
about your
1/1 [==============================] - 0s 31ms/step
about your family
1/1 [==============================] - 0s 32ms/step
about your family will
1/1 [==============================] - 0s 31ms/step
about your family will get
1/1 [==============================] - 0s 20ms/step
about your family will get bigger
